version: '3'
services:
  faber:
    image: mcr.microsoft.com/vscode/devcontainers/python:0-3.9-bullseye
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - proxy-network
    volumes:
      - ../..:/workspace
  nginx:
    image: nginx
    depends_on:
      - faber
    networks:
      - proxy-network
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
networks:
  proxy-network:
    driver: bridge
