version: '3'
services:
  faber:
    image: mcr.microsoft.com/vscode/devcontainers/python:0-3.9-bullseye
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      ngrok:
        condition: service_healthy
    networks:
      - proxy-network
    volumes:
      - ../..:/workspace
  nginx:
    image: nginx
    depends_on:
      - faber
    networks:
      - proxy-network
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
  ngrok:
    image: ngrok/ngrok
    command: start --all
    environment:
      NGROK_CONFIG: /etc/ngrok.yml
    healthcheck:
      test: /bin/bash -c "</dev/tcp/ngrok/4040"
      interval: 3s
      timeout: 3s
      start_period: 5s
      retries: 5
    hostname: ngrok
    networks:
      - proxy-network
    restart: unless-stopped
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
networks:
  proxy-network:
    driver: bridge
